### ISSUE TITLE
CUDA error during training

### ISSUE THREAD

**Issue by cm56uw** [traveller59/second.pytorch#229]
Hi, thanks for sharing the work! During the training a CUDA error happened after 49450 steps with batch size of 3.
cudahash: Completely failed to build
Cuda error in file '/home/hjus/spconv/src/cuhash/hash_table.cpp' in line 194 : an illegal memory access was encountered.

**Comment by robin2002** [comment]
I also got the same error. Have anyone solved this issue?

**Comment by shuluoshu** [comment]
Me too, after training for 36400 steps, I got the same error. 

> Cuda error , an illegal memory access was encountered.

**Comment by cm56uw** [comment]
Not solved yet. I have tried several times with spconv middle layer. It seems only happened when using nusences dataset, KITTI is fine. Trainning with pointpillar's config to bypass the spconv works well.

**Comment by wyjforwjy** [comment]
I also got this error.And I train by muti-gpu.

**Comment by shuluoshu** [comment]
> Not solved yet. I have tried several times with spconv middle layer. It seems only happened when using nusences dataset, KITTI is fine. Trainning with pointpillar's config to bypass the spconv works well.

I am using KITTI Dataset, and I also got that error, both multi-gpu and  single fail!

**Comment by qchenclaire** [comment]
Me too, with KITTI and SECOND. Seems to happen randomly

**Comment by He-Yunqian** [comment]
me too， with KITTI dataset

**Comment by turboxin** [comment]
me too with custom dataset

**Comment by nslay** [comment]
The illegal memory access problem happens for non-KITTI and non-nuscenes data. This seems like a memory corruption problem. Maybe use -fsanitize=address in compilation and see what happens? I will try it myself.

**Comment by jianrenw** [comment]
I changed 
https://github.com/traveller59/spconv/blob/master/src/cuhash/hash_table.cpp#L102
to: table_size_ = unsigned(floor(max_table_entries * space_usage) + 1);
It works for me

**Comment by jianrenw** [comment]
Same problem. I wrote a bash to restart the code automatically.
=====================================================
#!/bin/sh

while true; do
  sed -i 's/}}{/}}\n{/g' ./checkpoints/log.json.lst
  python ./pytorch/train.py train --config_path=./configs/nuscenes/all.fhd.config --model_dir=./checkpoints --resume=True
done &
=====================================================
Not a good solution, but at least can run the code.

**Comment by HenryJunW** [comment]
Same error with Kitti dataset w/ multiple GPUs, any solutions so far?

**Comment by reveriel** [comment]
try
```python
 SpConv3d = change_default_args(bias=False, use_hash=False)(spconv.SparseConv3d)
 SubMConv3d = change_default_args(bias=False, use_hash=False)(spconv.SubMConv3d)
```

seems working for me.
